### ISSUE TITLE
Sprint/Features List

### ISSUE THREAD

**Issue by hughesd22** [TraceLarson/WD6-ProjectPorfolio#10]
**Describe the solution you'd like**
Using the attached template in FSO titled *WD6_AgileSprints_ProductFeatureList-Backlogv3.xls* create a list of features that we plan to develop in the upcoming Sprint.

**Describe alternatives you've considered**
There are no alternatives. This is a requirement for our Week 2 Stand Up.

**Comment by DeveloperFia** [comment]
Nice team work!  Thanks Team 3Commerce :-)
