### ISSUE TITLE
Shopping Cart CRUD

### ISSUE THREAD

**Issue by csfiedor** [TraceLarson/WD6-ProjectPorfolio#15]
As a user, I want to be able to add, update and delete items from the shopping cart.

**Comment by hughesd22** [comment]
35d45ec9a59a6633446603af33f70b9dd9437475

e0e10dc5b84687c5c5e089b834c8104b7cb4c9f8

25b8cb1f9cf2f23f50a473848692618e777a43cc

**Comment by csfiedor** [comment]
Dan, please leave this open. Your solution can not be integrated and does not solve the issue for the established group project.

**Comment by hughesd22** [comment]
The group project has already been completed, minus you and Trace's add-on features. It's your choice to continue to work on a React alternative which won't integrate with the completed group project.

This feature has already been completed.

See:

- 35d45ec9a59a6633446603af33f70b9dd9437475
- e0e10dc5b84687c5c5e089b834c8104b7cb4c9f8
- 25b8cb1f9cf2f23f50a473848692618e777a43cc

Thanks for your understanding.
