### ISSUE TITLE
Stripe API payment/verification

### ISSUE THREAD

**Issue by csfiedor** [TraceLarson/WD6-ProjectPorfolio#16]
As a user, I want to be able to checkout an item and complete my transaction from the shopping cart.

**Comment by hughesd22** [comment]
cbc71e40582b6966e986e98645022c0f5cfb9965

**Comment by hughesd22** [comment]
cbc71e40582b6966e986e98645022c0f5cfb9965

**Comment by csfiedor** [comment]
Dan, please leave this open. Your solution can not be integrated and does not solve the issue for the established group project.

**Comment by hughesd22** [comment]
I completed the group project already, minus you and Trace's add-on features. It's your choice to keep working on a React alternative, which won't integrate with the finished project.

See cbc71e40582b6966e986e98645022c0f5cfb9965 for further information.

Thanks.
