### ISSUE TITLE
Save for Later (Wish List)

### ISSUE THREAD

**Issue by hughesd22** [TraceLarson/WD6-ProjectPorfolio#23]
**Describe the solution you'd like**
As a user, I'd like to be able to save an order to return to later if I don't have enough time to complete the purchase. Having a sort of "wish list" to store products would solve this issue.

**Comment by csfiedor** [comment]
This is immature and an attempt to hijack the group project. Good luck going forward.

**Comment by hughesd22** [comment]
? Have you finished your add-on feature already? If so just comment the commit # and close the issue. This is to help us track progress.

**Comment by hughesd22** [comment]
"Hijack the group project" I mean, I put in my work. I'm going to stop responding to you though after this, it only seems to make you angry for some reason. Good luck with the rest of your development career, I truly mean that.

<img width="1713" alt="wakatime" src="https://user-images.githubusercontent.com/11495741/47001399-30cfa880-d0df-11e8-848e-659094c320ce.png">

See: https://github.com/TraceLarson/WD6-ProjectPortfolio/tree/GameDrop-handlebars
